<?php

namespace Karronoli\Salesforce\Tests;

use Carbon\Carbon;

class AccessTokenTest extends TestCase {

    public function setUp()
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        Carbon::setTestNow('2018-12-30 10:10:00');
    }

    /** @test */
    public function can_create_access_token()
    {
        $issueDate  = \Carbon\Carbon::now();
        $expiryDate = \Carbon\Carbon::now()->addHour();

        $token = new \Karronoli\Salesforce\AccessToken(
            'abc123',
            $issueDate,
            $expiryDate,
            ['scopes'],
            'refresh-token',
            'signature',
            'access-token',
            'http://example.com'
        );

        $this->assertInstanceOf(\Karronoli\Salesforce\AccessToken::class, $token);

        $this->assertEquals('access-token', $token->accessToken());
        $this->assertEquals('refresh-token', $token->refreshToken());
        $this->assertEquals('http://example.com', $token->apiUrl());
        $this->assertEquals(['scopes'], $token->scopes());
    }

    /** @test */
    public function token_refresh_is_correct()
    {
        $token1 = new \Karronoli\Salesforce\AccessToken(
            'abc123',
            \Carbon\Carbon::now(),
            \Carbon\Carbon::now()->addHour(),
            ['scopes'],
            'refresh-token',
            'signature',
            'access-token',
            'http://example.com'
        );

        $this->assertFalse($token1->needsRefresh());

        $token2 = new \Karronoli\Salesforce\AccessToken(
            'abc123',
            \Carbon\Carbon::now()->subHours(2),
            \Carbon\Carbon::now()->subHour(),
            ['scopes'],
            'refresh-token',
            'signature',
            'access-token',
            'http://example.com'
        );
        $this->assertTrue($token2->needsRefresh());
    }

    /** @test */
    public function can_convert_to_json()
    {
        $token = new \Karronoli\Salesforce\AccessToken(
            'abc123',
            \Carbon\Carbon::now(),
            \Carbon\Carbon::now()->addHour(),
            ['scopes'],
            'refresh-token',
            'signature',
            'access-token',
            'http://example.com'
        );

        $this->assertJsonStringEqualsJsonString('{"id":"abc123","dateIssued":"2018-12-30 10:10:00","dateExpires":"2018-12-30 11:10:00","scope":["scopes"],"refreshToken":"refresh-token","signature":"signature","accessToken":"access-token","apiUrl":"http:\/\/example.com"}', $token->toJson(), 'Token casts to a json string');
    }

    /** @test */
    public function updates_correctly()
    {
        $token = new \Karronoli\Salesforce\AccessToken(
            'abc123',
            \Carbon\Carbon::now(),
            \Carbon\Carbon::now()->addHour(),
            ['scopes'],
            'refresh-token',
            'signature',
            'access-token',
            'http://example.com'
        );


        $time = 1429281826;

        $token->refresh([
            'issued_at' => $time,
            'signature' => 'new-signature',
            'access_token' => 'new-access-token'
        ]);

        $this->assertEquals('new-access-token', $token->accessToken(), 'access token was not updated');
        $this->assertInstanceOf(\Carbon\Carbon::class, $token->dateExpires());
        $this->assertInstanceOf(\Carbon\Carbon::class, $token->dateIssued());
        $this->assertEquals($time, $token->dateIssued()->timestamp, 'Timestamp saved and converted incorrectly');
    }
}
